[package]
name = "buildomat"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = { workspace = true }
buildomat-common = { path = "../common" }
buildomat-client = { path = "../client" }
bytes = { workspace = true }
cargo_metadata = { workspace = true }
chrono = { workspace = true }
dirs-next = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
hiercmd = { workspace = true }
hmac-sha256 = { workspace = true }
rusty_ulid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
snapbox = { workspace = true }
tempfile = { workspace = true }
